In [1]:
import torch

In [2]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape)
print(x[0,:].shape)  # equivalent

torch.Size([25])
torch.Size([25])


In [5]:
print(x[:, 0].shape)
print(x[2, 0:5].shape)

x[0, 0] = 100  # set a value

torch.Size([10])
torch.Size([5])


In [8]:
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

tensor([2, 5, 8])


In [9]:
x = torch.rand((3, 5))
print(x)
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
# x[1,4], x[0,0]
print(x[rows, cols])

tensor([[0.8460, 0.4197, 0.3795, 0.5340, 0.8654],
        [0.1979, 0.8595, 0.1366, 0.5371, 0.9240],
        [0.4928, 0.2746, 0.8365, 0.3670, 0.7453]])
tensor([0.9240, 0.8460])


In [14]:
x = torch.tensor([1, 3, 5, 7, 8, 10])
print(x[(x < 2) | (x > 8)])
print(x[(x < 2) & (x > 8)])
print(x[x.remainder(2) == 0])  # pick up all the even elements

tensor([ 1, 10])
tensor([], dtype=torch.int64)
tensor([ 8, 10])


`where(condition, input, other, *, out=None) -> Tensor`
`condition`: When `True` (nonzero), yield `input`, otherwise yield `other`

In [15]:
x = torch.arange(10)
print(torch.where(x > 5, x / 2, x * 2))

tensor([ 0.0000,  2.0000,  4.0000,  6.0000,  8.0000, 10.0000,  3.0000,  3.5000,
         4.0000,  4.5000])


In [16]:
x = torch.tensor([0, 0, 1, 1])
print(x.unique())

tensor([0, 1])


In [19]:
x = torch.rand((5, 5, 5))
print(x.ndimension())
print(x.numel())  # number of elements in the tensor

3
125
