Addition:

In [1]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [2]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

tensor([10., 10., 10.])


An alternative way is:

In [3]:
z2 = torch.add(x, y)
print(z2)

tensor([10, 10, 10])


Or we can use:

In [4]:
print(x + y)

tensor([10, 10, 10])


Subtraction:

In [5]:
print(x - y)

tensor([-8, -6, -4])


Division:

In [7]:
# element-wise division if x and y are of the same shape
z = torch.true_divide(x, y)
print(z)

# x = torch.tensor([1, 2, 3])
# z2 = torch.tensor([1/2, 2/2, 3/2])
z2 = torch.true_divide(x, 2)
print(z2)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.5000, 1.0000, 1.5000])


Inplace operations: more computationally efficient

In [9]:
t = torch.zeros(3)
print(t)

# function name followed by underline indicates that it's inplace
t.add_(x)  # or alternatively: t += x
print(t)

tensor([0., 0., 0.])
tensor([1., 2., 3.])


Exponentiation:

In [11]:
# element-wise power of 2
z = x.pow(2)
print(z)

z2 = x ** 2  # equivalent
print(z2)

tensor([1, 4, 9])
tensor([1, 4, 9])


Element-wise Comparison:

In [14]:
z = x > 1  # x = [1, 2, 3]
print(z)
z = x <= 1
print(z)

tensor([False,  True,  True])
tensor([ True, False, False])


Matrix Multiplication:

In [15]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
print(x3)
x4 = x1.mm(x2)  # equivalent
print(x4)
print(x3 == x4)

tensor([[0.8700, 1.6029, 1.0622],
        [1.2484, 1.9030, 1.0377]])
tensor([[0.8700, 1.6029, 1.0622],
        [1.2484, 1.9030, 1.0377]])
tensor([[True, True, True],
        [True, True, True]])


Matrix Exponentiation:

In [16]:
matrix_exp = torch.rand((5, 5))
z = matrix_exp.matrix_power(3)

org = matrix_exp
z2 = matrix_exp.mm(matrix_exp).mm(org)  # equivalent
print(z == z2)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


Element-wise multiplication:

In [17]:
print("x", x)
print("y", y)

print("z", x * y)

x tensor([1, 2, 3])
y tensor([9, 8, 7])
z tensor([ 9, 16, 21])


Dot product:

In [18]:
print(torch.dot(x, y))

tensor(46)


Batch Matrix Multiplication:

Performs a batch matrix-matrix product of matrices stored in `input` and `mat2`.

`input` and `mat2` must be 3-D tensors each containing the same number of matrices.

In [20]:
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)  # (batch, n, p)
print(out_bmm.shape)

torch.Size([32, 10, 30])


Examples of Broadcasting:

Every row of `x1` is subtracted by the only row in `x2`.

In [23]:
x1 = torch.rand((2, 2))
print("x1", x1)
x2 = torch.rand((1, 2))
print("x2", x2)
print("z", x1 - x2)
print("z2", x1 ** x2)

x1 tensor([[0.2050, 0.3851],
        [0.8972, 0.4336]])
x2 tensor([[0.7753, 0.1034]])
z tensor([[-0.5703,  0.2817],
        [ 0.1218,  0.3302]])
z2 tensor([[0.2927, 0.9061],
        [0.9193, 0.9172]])


Other useful tensor operations:

In [29]:
tensor = torch.rand((2, 2, 2))
print(tensor)
# Returns the sum of each row of the input tensor in the given
# dimension dim. If dim is a list of dimensions, reduce over all of them.
print(torch.sum(tensor, dim=0))
print(torch.sum(tensor, dim=1))
print(torch.sum(tensor, dim=2))

tensor([[[0.1585, 0.7323],
         [0.3606, 0.5413]],

        [[0.1707, 0.6138],
         [0.6091, 0.0805]]])
tensor([[0.3292, 1.3461],
        [0.9697, 0.6218]])
tensor([[0.5191, 1.2736],
        [0.7799, 0.6943]])
tensor([[0.8908, 0.9019],
        [0.7845, 0.6896]])


`max`, `argmax`, `min`:

In [42]:
tensor = torch.rand((2, 2, 2))
print(tensor)

values, indices = torch.max(tensor, dim=0)  # equivalently: tensor.max(dim=0)
print("max values:", values)
print("max indices:", indices)
print(indices == torch.argmax(tensor, dim=0))
print("====================================")
values, indices = torch.min(tensor, dim=0)
print("min values:", values)
print("min indices:", indices)
print(indices == torch.argmin(tensor, dim=0))

tensor([[[0.1578, 0.6950],
         [0.8050, 0.1457]],

        [[0.4656, 0.2618],
         [0.9898, 0.9719]]])
max values: tensor([[0.4656, 0.6950],
        [0.9898, 0.9719]])
max indices: tensor([[1, 0],
        [1, 1]])
tensor([[True, True],
        [True, True]])
min values: tensor([[0.1578, 0.2618],
        [0.8050, 0.1457]])
min indices: tensor([[0, 1],
        [0, 0]])
tensor([[True, True],
        [True, True]])


Element-wise absolute value:

In [36]:
tensor = torch.tensor([-1, -2, -3])
print(torch.abs(tensor))

tensor([1, 2, 3])


Note that `torch.mean()` requires us to use `float` numbers:

In [44]:
tensor = torch.rand((2, 2)).float()
print(tensor)

mean_tensor = torch.mean(tensor, dim=0)
print(mean_tensor)

tensor([[0.8388, 0.1203],
        [0.5127, 0.0272]])
tensor([0.6758, 0.0737])


In [45]:
print(torch.eq(x, y))

tensor([False, False, False])


In [49]:
tensor = torch.rand((3, 3))
print(tensor)
tensor, indices = torch.sort(tensor, dim=0, descending=False)
print(tensor)
print(indices)

tensor([[0.5421, 0.8342, 0.5736],
        [0.1381, 0.4777, 0.6277],
        [0.9441, 0.9562, 0.5587]])
tensor([[0.1381, 0.4777, 0.5587],
        [0.5421, 0.8342, 0.5736],
        [0.9441, 0.9562, 0.6277]])
tensor([[1, 1, 2],
        [0, 0, 0],
        [2, 2, 1]])


Note that `torch.clamp(tensor, min=0)` is exactly the **RELU** function.

In [51]:
tensor = torch.tensor([1, -1, 3, 11])
z = torch.clamp(tensor, min=0, max=10)
print(z)

tensor([ 1,  0,  3, 10])


In [52]:
bool_tensor = torch.tensor([1, 0, 0], dtype=torch.bool)
print(torch.any(bool_tensor))
print(torch.all(bool_tensor))

tensor(True)
tensor(False)
