In [1]:
import torch

## Contiguous Tensors in PyTorch

In the context of PyTorch and tensor operations, "contiguous" refers to the way data is stored in memory. A contiguous tensor is one where the elements are stored in a contiguous block of memory, with no gaps between them. This means that the stride (the step size between elements) is consistent and follows the order of the tensor's dimensions.

### Example of a Contiguous Tensor

Consider a simple 2D tensor (matrix):

```python
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
```

In memory, the elements of this tensor are stored in a contiguous block as follows:

```
1 2 3 4 5 6
```

Here, the elements are laid out one after the other in memory, which makes the tensor contiguous.

### Example of a Non-Contiguous Tensor

A tensor can become non-contiguous after certain operations, such as transposing. For example:

```python
y = x.t()  # Transpose the tensor
```

The transposed tensor `y` will look like this:

```python
tensor([[1, 4],
        [2, 5],
        [3, 6]])
```

However, in memory, the elements are still stored in the original order:

```
1 2 3 4 5 6
```

But to access the elements of `y`, you need to skip certain elements, making the access pattern non-contiguous.

### Checking for Contiguity

You can check if a tensor is contiguous using the `is_contiguous()` method:

```python
print(x.is_contiguous())  # True
print(y.is_contiguous())  # False
```

### Why Contiguity Matters

- **Performance**: Operations on contiguous tensors are generally faster because the data is stored in a straightforward manner, allowing for better memory access patterns.
- **View Operation**: The `view()` function in PyTorch requires the tensor to be contiguous because it directly reshapes the tensor without copying the data. (`shape()` does not require the tensor to be contiguous so it's a safe option).

### Making a Tensor Contiguous

If you need to make a non-contiguous tensor contiguous, you can use the `contiguous()` method:

```python
y_contiguous = y.contiguous()
print(y_contiguous.is_contiguous())  # True
```

This method returns a new tensor that is a contiguous copy of the original tensor.

In [3]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)  # x has to be contiguous
print(x_3x3)

x_3x3_2 = x.reshape(3, 3)
print(x_3x3_2)  # nearly equivalent

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [4]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [5]:
# unroll
matrix = torch.rand(2, 2)
print(matrix)
flattened = matrix.view(-1)
print(flattened)

tensor([[0.2878, 0.7538],
        [0.5410, 0.1090]])
tensor([0.2878, 0.7538, 0.5410, 0.1090])


In [6]:
batch = 64
dataset = torch.rand(batch, 2, 4)
dataset2 = dataset.view(batch, -1)
print(dataset2.shape)

torch.Size([64, 8])


Tranpose `tensor.t()` is just a special case of `tensor.permute()`. We can use `permute()` when dealing with complicated high-dimensional tensors.

In [8]:
dataset = torch.rand(batch, 2, 4)
dataset3 = dataset.permute(0, 2, 1)
print(dataset3.shape)

torch.Size([64, 4, 2])


In [24]:
x = torch.arange(10)
print(x, x.shape)
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print(x.unsqueeze(1), x.unsqueeze(1).shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 10])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([10, 1])


In [25]:
z = x.unsqueeze(0).unsqueeze(1)
print(z.shape)
z2 = z.squeeze(0)
print(z2.shape)
z3 = z2.squeeze(0)
print(x.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
torch.Size([10])
