In [1]:
import torch

Create a tensor using 2d list:

You can also set `device="cuda"` or `device="cpu"` in `torch.tensor`.

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor_init = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device, requires_grad=False)
print(my_tensor_init)

tensor([[1, 2, 3],
        [4, 5, 6]])


`print(my_tensor_float.device)` will show `cuda:0` if you have GPU. Here, `0` represents the **first** GPU.

In [15]:
my_tensor_float = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, requires_grad=True)

print(my_tensor_float)
print(my_tensor_float.dtype)
print(my_tensor_float.device)
print(my_tensor_float.shape)
print(my_tensor_float.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


Creating a tensor filled with random values (that were already in the memory) by specifying the shape. It is *not* necessarily filled with $0$.

In [16]:
empty_tensor = torch.empty(size=(3, 3))
print(empty_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


We can also create a tensor of zeros.

In [17]:
zero_tensor = torch.zeros((3, 3))
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Other methods:

In [18]:
# Returns a tensor filled with random numbers from a uniform distribution
# on the interval [0, 1)
uniform_torch = torch.rand((3, 3))
print(uniform_torch)

tensor([[0.5027, 0.7261, 0.0394],
        [0.4156, 0.1593, 0.1515],
        [0.5785, 0.0022, 0.4127]])


In [29]:
ones_torch = torch.ones((3, 3))
print(ones_torch)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
id_torch = torch.eye(5, 5)  # eye for I: identity matrix
print(id_torch)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Note that `end` is **exclusive** here.

In [24]:
arange_torch = torch.arange(start=0, end=5, step=1)
print(arange_torch)
print(f"shape (1-D): {arange_torch.shape}")

tensor([0, 1, 2, 3, 4])
shape (1-D): torch.Size([5])


Note that `end` is **inclusive** here.

In [26]:
linspace_torch = torch.linspace(start=0.1, end=1, steps=10)
print(linspace_torch)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [30]:
# Fills self tensor with elements samples from
# the normal distribution parameterized by mean and std.
norm_torch = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(norm_torch)

# unform_(form_:, to:)
# Fills self tensor with numbers sampled from the continuous uniform distribution
uniform_torch_2 = torch.empty(size=(1, 5)).uniform_(0, 1)
print(uniform_torch_2)

tensor([[-0.2278, -2.0400,  0.2165, -0.2985, -0.5170]])
tensor([[0.2622, 0.1769, 0.3056, 0.5632, 0.8008]])


In [31]:
x = torch.tensor([1, 2, 3])
diag_tensor = torch.diag(x)
print(diag_tensor)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


How to initialize and convert tensor to different types: **int, float, double**, etc

In [37]:
int64_tensor = torch.arange(4)
print(int64_tensor)

print(int64_tensor.bool())  # convert 0 to F, others to T

print(int64_tensor.short())  # convert to int_16

# convert to int_64 (default, frequently used)
print(int64_tensor.long())

# convert to float_16, this is often used with GPUs
print(int64_tensor.half())

# convert to float_32 (default, frequently used)
print(int64_tensor.float())

print(int64_tensor.double())  # convert to float_64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


Array to Tensor conversion and vice-versa:

In [39]:
import numpy as np

np_array = np.zeros((5, 5))
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
